Consulte_poste/urls.py
from django.urls import path
from .views import HomeView
from .views import MaisonsDetailsViews
from .views import AboutViews
from .views import UserUpdateView 
from .views import AddVillaViews
from .views import AddReservation
from .views import PasswordsViews
from .views import PersonalVillaView
from .views import VillaUpdateView
from .views import ReservationUpdateView
from .views import UserDeleteView
from .views import VillaDeleteView
from .views import ReservationDeleteView , Reservation1DeleteADView , searchbar
from .views import ListeVillaView  , Reservation1UpdateADView
from .views import ListeUserView , AddADReservation , AddADReservation2
from .views import ListeReservationView , AddAppADViews ,ReservationDeleteADView
from .views import HomeAppartView
from .views import AppDetailsViews , AppUpdateADView , AppDeleteADView ,ReservationUpdateADView
from .views import AddReservation2
from .views import AddAppViews , AppUpdateView , PersonalAppView , AppDeleteView , Reservation1DeleteView , Reservation1UpdateView , ListePersReservation1View , ListePersReservation2View ,ListeAppView ,ListeReservation1View ,HomeI , UserADUpdateView , PasswordsADViews , VillaADUpdateView , VillaADDeleteView , AddVillaADDViews

from .import views
from django.contrib.auth.views import LoginView , LogoutView
from django.contrib.auth import views as auth_views

app_name ='Consulte_poste'
urlpatterns = [
    path('home0/', HomeI.as_view() , name="homeIn"), 
    path('home/', HomeView.as_view() , name="home"),
    path('home1/', HomeAppartView.as_view() , name="home-Appar"),
    path('details/<int:pk>/', MaisonsDetailsViews.as_view() , name = 'Maison-details') ,
    path('details1/<int:pk>/', AppDetailsViews.as_view() , name = 'App-details') ,
    path('about/', AboutViews.as_view() , name="About-site"),
    path('update/<int:pk>/', UserUpdateView.as_view(), name="Update-user"),
    path('updateUA/<int:pk>/', UserADUpdateView.as_view(), name="Update-userAD"),
    path('addvilla/', AddVillaViews.as_view(), name="Add-villa"),
    path('addvillaAD/', AddVillaADDViews.as_view(), name="Add-villaAD"),
    path('addapp/', AddAppViews.as_view(), name="Add-App"),
    path('addappAD',AddAppADViews.as_view(),name="AddAD-App"),
    path('addreservation/<int:pk>/', AddReservation.as_view() , name="Add-Reservation") ,
    path('addADreservation/', AddADReservation.as_view() , name="Add-ReservationAD") ,
    path('addreservation2/<int:pk>/', AddReservation2.as_view() , name="Add-Reservation2") ,
    path('addADreservation2/', AddADReservation2.as_view() , name="AddAD-Reservation2") ,
    path('password/', PasswordsViews.as_view(template_name='registration/changepassword.html') , name="Pass-change"),
    path('passwordAD/', PasswordsViews.as_view( template_name='registration/changepasswordAD.html') , name="Pass-changeAD"),
    path('listpersonalvilla/',PersonalVillaView.as_view(), name='Liste-Pvilla'),
    path('listpersonalapp/',PersonalAppView.as_view(), name='Liste-PApp'),
    path('updatevilla/<int:pk>/' , VillaUpdateView.as_view(),name='Update-villa'),
    path('updatevillaAD/<int:pk>/' , VillaADUpdateView.as_view(),name='UpdateAD-villa'),
    path('updateapp/<int:pk>/' , AppUpdateView.as_view(),name='Update-App'),
    path('updateADapp/<int:pk>/' , AppUpdateADView.as_view(),name='UpdateAD-App'),
    path('updatereservation/<int:pk>/' , ReservationUpdateView.as_view(),name='Update-reservation' ),
    path('updateADreservation/<int:pk>/' , ReservationUpdateADView.as_view(),name='UpdateAD-reservation' ),
    path('updatereservation1/<int:pk>/' , Reservation1UpdateView.as_view(),name='Update-reservation1' ),
    path('updateADreservation1/<int:pk>/' , Reservation1UpdateADView.as_view(),name='Update-reservationAD1' ),
    path('deleteuser/<int:pk>/', UserDeleteView.as_view(),name="Delete-user"),
    path('deletevilla/<int:pk>/', VillaDeleteView.as_view(),name="Delete-villa"),
    path('deletevillaAD/<int:pk>/', VillaADDeleteView.as_view(),name="DeleteAD-villa"),
    path('deleteapp/<int:pk>/', AppDeleteView.as_view(),name="Delete-App"),
    path('deleteappAD/<int:pk>/', AppDeleteADView.as_view(),name="DeleteAD-App"),
    path('deletereservation/<int:pk>/', ReservationDeleteView.as_view(),name="Delete-reservation"),
    path('deleteADreservation/<int:pk>/', ReservationDeleteADView.as_view(),name="DeleteAD-reservation"),
    path('deletereservation1/<int:pk>/', Reservation1DeleteView.as_view(),name="Delete-reservation1"),
    path('deleteADreservation1/<int:pk>/', Reservation1DeleteADView.as_view(),name="DeleteAD-reservation1"),
    path('listevilla/',ListeVillaView.as_view(),name="Liste-villa"),
    path('listeapp/',ListeAppView.as_view(),name="Liste-app"),
    path('listeuser/',ListeUserView.as_view(),name="Liste-user"),
    path('listereservationvilla/',ListeReservationView.as_view(),name="Liste-ReserVilla"),
    path('listereservationapp/',ListeReservation1View.as_view(),name="Liste-Reserapp"),
    path('listeperreser1/',ListePersReservation1View.as_view(),name="Liste-PersReserVil"),
    path('listeperreser2/',ListePersReservation2View.as_view(),name="Liste-PersReserApp"),
    path('searchbar/',views.searchbar , name='searchbar')

]

MyProjectHouses/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Consulte_poste.urls')),
    path('', include('registration.urls')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

registration/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView , LogoutView
from .views import RegistreViews , RegistreViewsAD

urlpatterns = [
    
   
    path('login/', LoginView.as_view() , name ='Login') ,
    path('logout/', LogoutView.as_view() , name ='Logout') ,
    path('registre/', RegistreViews.as_view() , name ='Registre') ,
    path('registreAD/', RegistreViewsAD.as_view() , name ='RegistreAD') ,

    

]

Consulte_poste/views.py
#from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse 
from django.shortcuts import render
from django.views.generic import View , TemplateView , ListView , DetailView , FormView , UpdateView 
from django.contrib.auth.forms import UserChangeForm  
#from django.http import HttpResponse
from .models import Villa 
from .models import ResrvationVilla
from .models import ResrvationAppartement
from .models import Appartement
from django.contrib.auth.models import User 
from django.views.generic.edit import CreateView 
from django.views.generic.edit import DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
from django.contrib.auth.views import PasswordChangeView 








class HomeI(TemplateView):
    template_name = 'Home0.html'


class HomeView(ListView):
    template_name = 'Home.html'
    model = Villa

class HomeAppartView(ListView):
    template_name = 'HomeAppart.html'
    model = Appartement

class PersonalVillaView(ListView):
    template_name = 'PersVillaList.html'
    model = Villa

class PersonalAppView(ListView):
    template_name = 'PersappList.html'
    model = Appartement

class ListeVillaView(ListView):
    template_name = 'listeVillaList.html'
    model = Villa
    context_object_name = 'a'

class ListeAppView(ListView):
    template_name = 'listeAppList.html'
    model = Appartement
    context_object_name = 'a'

class ListeUserView(ListView):
    template_name = 'listeUser.html'
    model = User
    context_object_name = 'a'

class ListeReservationView(ListView):
    template_name = 'listeReservation.html'
    model = ResrvationVilla
    context_object_name = 'a'



class ListeReservation1View(ListView):
    template_name = 'listeReservation1.html'
    model = ResrvationAppartement
    context_object_name = 'a'


class ListePersReservation1View(ListView):
    template_name = 'listePersReservation1.html'
    model = ResrvationVilla
    context_object_name = 'a'

class ListePersReservation2View(ListView):
    template_name = 'listePersReservation2.html'
    model = ResrvationAppartement
    context_object_name = 'a'
  


class MaisonsDetailsViews(DetailView):
    template_name = 'Details.html'
    model = Villa 
    context_object_name = 'a'

class AppDetailsViews(DetailView):
    template_name = 'DetailsApp.html'
    model = Appartement 
    context_object_name = 'a'





class AboutViews(TemplateView):
    template_name = 'About.html'


class UserUpdateView(UpdateView):
    template_name='UpdateUser.html'
    model = User
    fields = ["username"]
    success_url = '/home0/' 

class UserADUpdateView(UpdateView):
    template_name='UpdateUserAd.html'
    model = User
    fields = ["username"]
    success_url = '/listeuser/'

class UserDeleteView(DeleteView):
    template_name='deleteuser.html'
    model=User
    success_url = '/listeuser/'

class VillaUpdateView(UpdateView):
    template_name="Updatevilla.html"
    model=Villa
    fields=["Title","Description","Address","StartDay","EndDay","Image1","Image2","Image3","Image4","PrixDay","NumVilla","Piscine"]
    success_url='/listpersonalvilla/'

class VillaADUpdateView(UpdateView):
    template_name="UpdatevillaAD.html"
    model=Villa
    fields=["Title","Description","Address","StartDay","EndDay","Image1","Image2","Image3","Image4","PrixDay","NumVilla","Piscine"]
    success_url='/listevilla/'


class AppUpdateView(UpdateView):
    template_name="Updateapp.html"
    model=Appartement
    fields=["Title","Description","Address","StartDay","EndDay","Image1","Image2","Image3","Image4","PrixDay","NumImmeble","NumEtage","NumAppartement"]
    success_url='/listpersonalapp/'

class AppUpdateADView(UpdateView):
    template_name="UpdateADapp.html"
    model=Appartement
    fields=["Title","Description","Address","StartDay","EndDay","Image1","Image2","Image3","Image4","PrixDay","NumImmeble","NumEtage","NumAppartement"]
    success_url='/listeapp/'

class VillaDeleteView(DeleteView):
    template_name='deletevilla.html'
    model=Villa
    context_object_name = 'a'
    success_url = '/listpersonalvilla/'


class VillaADDeleteView(DeleteView):
    template_name='deletevillaAD.html'
    model=Villa
    context_object_name = 'a'
    success_url = '/listevilla/'

class AppDeleteView(DeleteView):
    template_name='deleteapp.html'
    model=Appartement
    context_object_name = 'a'
    success_url = '/listpersonalapp/'

class AppDeleteADView(DeleteView):
    template_name='deleteappAD.html'
    model=Appartement
    context_object_name = 'a'
    success_url = '/listeapp/'

class ReservationUpdateView(UpdateView):
    template_name="Updatereservation.html"
    model=ResrvationVilla
    fields = ["house","StartDayReser","EndDayReser"]
    success_url='/listeperreser1/'

class ReservationUpdateADView(UpdateView):
    template_name="UpdatereservationAD.html"
    model=ResrvationVilla
    fields = ["user","house","StartDayReser","EndDayReser"]
    success_url='/listereservationvilla/'

class Reservation1UpdateView(UpdateView):
    template_name="Updatereservation1.html"
    model=ResrvationAppartement
    fields = ["house","StartDayReser","EndDayReser"]
    success_url='/listeperreser2/'

class Reservation1UpdateADView(UpdateView):
    template_name="UpdatereservationAD1.html"
    model=ResrvationAppartement
    fields = ["user","house","StartDayReser","EndDayReser"]
    success_url='/listereservationapp/'

class ReservationDeleteView(DeleteView):
    template_name='deletereservation.html'
    model=ResrvationVilla
    context_object_name = 'a'
    success_url = '/listeperreser1/'

class ReservationDeleteADView(DeleteView):
    template_name='deleterADeservation.html'
    model=ResrvationVilla
    context_object_name = 'a'
    success_url = '/listereservationvilla/'

class Reservation1DeleteView(DeleteView):
    template_name='deletereservation1.html'
    model=ResrvationAppartement
    context_object_name = 'a'
    success_url = '/listeperreser2/'

class Reservation1DeleteADView(DeleteView):
    template_name='deleteADreservation1.html'
    model=ResrvationAppartement
    context_object_name = 'a'
    success_url = '/listereservationapp/'

class PasswordsViews(PasswordChangeView):
    success_url = '/home0/'

class PasswordsADViews(PasswordChangeView):
   
    success_url = '/listeuser/'

class AddVillaViews(CreateView):
    template_name = 'AddVilla.html'
    model = Villa
    fields = ["Title","Description","Address","StartDay","EndDay","Image1","Image2","Image3","Image4","PrixDay","NumVilla","Piscine"]
    success_url = '/home/'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)
    
class AddVillaADDViews(CreateView):
    template_name = 'AddVillaAD.html'
    model = Villa
    fields = ["user","Title","Description","Address","StartDay","EndDay","Image1","Image2","Image3","Image4","PrixDay","NumVilla","Piscine"]
    success_url = '/listevilla/'
    

class AddAppViews(CreateView):
    template_name = 'AddApp.html'
    model = Appartement
    fields = ["Title","Description","Address","StartDay","EndDay","Image1","Image2","Image3","Image4","PrixDay","NumImmeble","NumEtage","NumAppartement"]
    success_url = '/home1/'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class AddAppADViews(CreateView):
    template_name = 'AddAppAD.html'
    model = Appartement
    fields = ["user","Title","Description","Address","StartDay","EndDay","Image1","Image2","Image3","Image4","PrixDay","NumImmeble","NumEtage","NumAppartement"]
    success_url = '/listeapp/'

class AddReservation(LoginRequiredMixin ,CreateView ):
    template_name = 'AddReservation.html'
    model = ResrvationVilla
    fields = ["house","StartDayReser","EndDayReser"]
    success_url = '/home/'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)
    
class AddADReservation(CreateView ):
    template_name = 'AddADReservation.html'
    model = ResrvationVilla
    fields = ["user","house","StartDayReser","EndDayReser"]
    success_url = '/listereservationvilla/'
    

class AddReservation2(LoginRequiredMixin ,CreateView ):
    template_name = 'AddReservation2.html'
    model = ResrvationAppartement
    fields = ["house","StartDayReser","EndDayReser"]
    success_url = '/home1/'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)
    

class AddADReservation2(LoginRequiredMixin ,CreateView ):
    template_name = 'AddReservationAD2.html'
    model = ResrvationAppartement
    fields = ["user","house","StartDayReser","EndDayReser"]
    success_url = '/listereservationapp/'
    
    

def searchbar(request):
    if request.method =='GET':
        search= request.GET.get('search')
        v=Villa.objects.all().filter(title=search)
        return render(request,'searchbar.html',{'v':v})

    

Consulte_poste/templates/Home0.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>rental of summer houses</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />

<style>
body{
  width: 100%;
  height: 100vh;
  background-image: url('{% static "viiiila.jpeg" %}');
  background-repeat: no-repeat;
  background-size: cover;
  background-position: center;
  background-attachment: fixed;
}

</style>
    
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'Consulte_poste:homeIn' %}">rental of summer houses</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarColor01">
          <ul class="navbar-nav me-auto">
            <li class="nav-item">
              <a class="nav-link active" href="{% url 'Consulte_poste:homeIn' %}">Home
                <span class="visually-hidden">(current)</span>
              </a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="{% url 'Consulte_poste:About-site' %}">About</a>
            </li>
     
          </ul>
    
   
          

          <form class="d-flex">
     
            {% if user.is_authenticated %}
            <ul class="navbar-nav me-auto">
             

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">{{user}} ACTIONS</a>
                    <div class="dropdown-menu">
                      <a class="dropdown-item" href="{% url 'Consulte_poste:Add-villa' %}">Add your villa</a>
                      <a class="dropdown-item" href="{% url 'Consulte_poste:Add-App' %}">Add your appartment</a>
                      <a class="dropdown-item" href="{% url 'Consulte_poste:Liste-Pvilla' %}">Show your villas</a>
                      <a class="dropdown-item" href="{% url 'Consulte_poste:Liste-PApp' %}">Show your appartment</a>
                      <a class="dropdown-item" href="{% url 'Consulte_poste:Liste-PersReserVil' %}">Show all villa reservations </a>
                      <a class="dropdown-item" href="{% url 'Consulte_poste:Liste-PersReserApp' %}">Show all apartment reservations </a>
                      <a class="dropdown-item" href="{% url 'Consulte_poste:Update-user' user.id  %}">
                        Update Your Account Information </a>
                
                    </div>
                  </li>
               
                  {% if user.is_superuser %}
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">ADMIN ACTIONS</a>
                    <div class="dropdown-menu">
                      <a class="dropdown-item" href="{% url 'Consulte_poste:Liste-user' %}">Show all users</a>
                      <a class="dropdown-item" href="{% url 'Consulte_poste:Liste-villa' %}">Show all villas</a>
                      <a class="dropdown-item" href="{% url 'Consulte_poste:Liste-app' %}">Show all appartment</a>
                      <a class="dropdown-item" href="{% url 'Consulte_poste:Liste-ReserVilla' %}">Show all villa reservations</a>
                      <a class="dropdown-item" href="{% url 'Consulte_poste:Liste-Reserapp' %}">Show all apartment reservations</a>
                     
                
                    </div>
                  </li>
                  {% endif %}
                
 
            

                <li class="nav-item">
                  <a class="nav-link" href="{% url 'Logout' %}">LOGOUT</a>
                </li>
             </ul>
         
            {% else %}
            <ul class="navbar-nav me-auto">
             
            <li class="nav-item">
              <a class="nav-link" href="{% url 'Login' %}">LOGIN</a>
            </li>
              
            <li class="nav-item">
              <a class="nav-link" href="{% url 'Registre' %}">SIGNIN</a>
            </li>
           
         </ul>
  
            {% endif %}

       <form action="{% url 'Consulte_poste:searchbar' %}" method="get">
            <input class="form-control me-sm-2" type="text" name="Search"/>
            <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button></form>
          </form>
         </div>
      </div>
    </nav>

<br>
<br>
<br>
<br>
<br>
<br>

<h1 Align=Center style="color:#ffffff";><big>Your Dream Vacation</big></h1>

<h5 Align=Center style="color:#ffffff";><big>5000+ villas and appartments to rent in morocco </big></h5>
<br>
<br>

<br>
<br>
<div style="text-align:center">
    <a href="{% url 'Consulte_poste:home' %}"  >
    <button type="button" class="btn btn-primary">CONSULT OUR VILLAS</button>

    <a href="{% url 'Consulte_poste:home-Appar' %}"  >
    <button type="button" class="btn btn-secondary">CONSULT OUR APPARTMENTS</button>

</div>



  
<style> 
h1
{
font-size: 55px;
font-style:URW Chancery L, cursive
}
</style>







   



    
  


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>



  

  </body>
</html>

Consulte_poste/templates/PersVillaList.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>rental of summer houses</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />


    
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'Consulte_poste:homeIn' %}">rental of summer HOUSES</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarColor01">
          <ul class="navbar-nav me-auto">
            <li class="nav-item">
              <a class="nav-link active" href="{% url 'Consulte_poste:homeIn' %}">Home
                <span class="visually-hidden">(current)</span>
              </a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="#">About</a>
            </li>

          </ul>
    
   
          

          <form class="d-flex">
     
            {% if user.is_authenticated %}
            <ul class="navbar-nav me-auto">
             

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">{{user}} ACTIONS</a>
                    <div class="dropdown-menu">
                      <a class="dropdown-item" href="{% url 'Consulte_poste:Add-villa' %}">Add your villa</a>
                      <a class="dropdown-item" href="{% url 'Consulte_poste:Add-App' %}">Add your appartment</a>
                      <a class="dropdown-item" href="{% url 'Consulte_poste:Liste-Pvilla' %}">Show your villas</a>
                      <a class="dropdown-item" href="{% url 'Consulte_poste:Liste-PApp' %}">Show your appartment</a>
                      <a class="dropdown-item" href="{% url 'Consulte_poste:Liste-PersReserVil' %}">Show all villa reservations </a>
                      <a class="dropdown-item" href="{% url 'Consulte_poste:Liste-PersReserApp' %}">Show all apartment reservations </a>
                
                    </div>
                  </li>
               
                  {% if user.is_superuser %}
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">ADMIN ACTIONS</a>
                    <div class="dropdown-menu">
                      <a class="dropdown-item" href="{% url 'Consulte_poste:Liste-user' %}">Show all users</a>
                      <a class="dropdown-item" href="{% url 'Consulte_poste:Liste-villa' %}">Show all villas</a>
                      <a class="dropdown-item" href="{% url 'Consulte_poste:Liste-app' %}">Show all appartment</a>
                      <a class="dropdown-item" href="{% url 'Consulte_poste:Liste-ReserVilla' %}">Show all villa reservations</a>
                      <a class="dropdown-item" href="{% url 'Consulte_poste:Liste-Reserapp' %}">Show all apartment reservations</a>
                     
                
                    </div>
                  </li>
                  {% endif %}
                
 
            

                <li class="nav-item">
                  <a class="nav-link" href="{% url 'Logout' %}">LOGOUT</a>
                </li>
             </ul>
         
            {% else %}
            <ul class="navbar-nav me-auto">
             
            <li class="nav-item">
              <a class="nav-link" href="{% url 'Login' %}">LOGIN</a>
            </li>
              
            <li class="nav-item">
              <a class="nav-link" href="{% url 'Registre' %}">SIGNIN</a>
            </li>
           
         </ul>
  
            {% endif %}


            <input class="form-control me-sm-2" type="search" placeholder="Search">
            <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
          </form>
         </div>
      </div>
    </nav>









    {% block content %}
    <div class="container">
      <br>
      <br>
    <div class="row">
        {% with counter=0 %}
        {% endwith %}
          {% for Villa in object_list %}
          {% if user == Villa.user %}
          {% with counter=+1 %}
          {% endwith %}
          <div class="col-md-4">
            <div class="card">
              {% if Villa.Image1 %}
              <img src="{{ Villa.Image1.url }}" class="card-img-top" alt="..." >
              {% endif %}
              <div class="card-body">
                <h5 class="card-title">{{ Villa.Title }} </h5>
                <p class="card-text">{{ Villa.Description }}</p>
                <a href="{% url 'Consulte_poste:Maison-details' Villa.id %}" class="btn btn-sm btn-primary">Details</a>
                <a href="{% url 'Consulte_poste:Update-villa' Villa.id %}" class="btn btn-sm btn-primary">UPDATE</a>
                <a href="{% url 'Consulte_poste:Delete-villa' Villa.id %}" class="btn btn-sm btn-primary">DELETE</a>
              </div>
            </div>
          </div>
      
          {% if 'counter % 3' == 0 %}
      </div>
      <br>
      <br>
      <div class="row">
  {% endif %}

  {% endif %}

          {% endfor %}
        </div>
      </div>
  
      {% endblock content %}

      

  <style>
  .cstm-height-card .card-img-top {
  height: 100px;
  object-fit: cover;
}


body{
          width: 100%;
          height: 100vh;
          background-image: url('{% static "dddddd.jpeg" %}');
          background-repeat: no-repeat;
          background-size: cover;
          background-position: center;
          background-attachment: fixed;
        }
    </style>


 



  


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>

  

  </body>
</html>